package Destarador;


import java.awt.AWTException;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.image.BufferedImage;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import java.time.Instant;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.graphics.image.LosslessFactory;
import org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alber
 */
public class Inicio extends javax.swing.JFrame {

    // Variables
    public static String codigo_caja = "";
    public static String codigo_palet = "";
    private String nombre_directorio;
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);   // Centrar pantalla
        this.setTitle("Inicio");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_peso = new javax.swing.JLabel();
        peso_bruto = new javax.swing.JTextField();
        titulo_cod_caja = new javax.swing.JLabel();
        cod_caja = new javax.swing.JTextField();
        titulo_inicio = new javax.swing.JLabel();
        boton_destarar = new javax.swing.JButton();
        titulo_neto = new javax.swing.JLabel();
        opciones = new javax.swing.JLabel();
        titulo_modificar = new javax.swing.JLabel();
        cod_caja_modificar = new javax.swing.JTextField();
        boton_modificar = new javax.swing.JButton();
        titulo_eliminar = new javax.swing.JLabel();
        cod_caja_eliminar = new javax.swing.JTextField();
        boton_eliminar = new javax.swing.JButton();
        boton_aniadir = new javax.swing.JButton();
        boton_consultar = new javax.swing.JButton();
        peso_neto = new javax.swing.JLabel();
        texto_num_cajas = new javax.swing.JLabel();
        num_caja = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        texto_cod_palet = new javax.swing.JLabel();
        cod_palet = new javax.swing.JTextField();
        texto_num_palet = new javax.swing.JLabel();
        num_palets = new javax.swing.JTextField();
        texto_modificar_palet = new javax.swing.JLabel();
        cod_palet_modificar = new javax.swing.JTextField();
        boton_modificar_palet = new javax.swing.JButton();
        boton_aniadir_palet = new javax.swing.JButton();
        texto_eliminar_palet = new javax.swing.JLabel();
        cod_palet_eliminar = new javax.swing.JTextField();
        boton_eliminar_palet = new javax.swing.JButton();
        boton_consultar_palet = new javax.swing.JButton();
        text_cod_caja1 = new javax.swing.JLabel();
        cod_caja1 = new javax.swing.JTextField();
        text_num_caja1 = new javax.swing.JLabel();
        num_caja1 = new javax.swing.JTextField();
        boton_elegir = new javax.swing.JButton();
        boton_capturar_pantalla = new javax.swing.JButton();
        ruta = new javax.swing.JTextField();
        save_result = new javax.swing.JLabel();
        boton_imprimir_pantalla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo_peso.setLabelFor(peso_bruto);
        titulo_peso.setText("Peso Bruto (en kilogramos):");

        peso_bruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_brutoActionPerformed(evt);
            }
        });

        titulo_cod_caja.setLabelFor(cod_caja);
        titulo_cod_caja.setText("Código de Caja tipo 1:");

        cod_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_cajaActionPerformed(evt);
            }
        });

        titulo_inicio.setBackground(new java.awt.Color(255, 255, 255));
        titulo_inicio.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo_inicio.setForeground(new java.awt.Color(0, 153, 204));
        titulo_inicio.setText("DESTARADOR");

        boton_destarar.setText("Destarar");
        boton_destarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_destararActionPerformed(evt);
            }
        });

        titulo_neto.setLabelFor(peso_neto);
        titulo_neto.setText("Peso Neto :");

        opciones.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        opciones.setText("OPCIONES:");
        opciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        titulo_modificar.setText("Introduzca el código de caja a modificar: ");

        cod_caja_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_caja_modificarActionPerformed(evt);
            }
        });

        boton_modificar.setText("Modificar Caja");
        boton_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificarActionPerformed(evt);
            }
        });

        titulo_eliminar.setText("Introduzca el código de caja a eliminar:");

        cod_caja_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod_caja_eliminarActionPerformed(evt);
            }
        });

        boton_eliminar.setText("Eliminar Caja");
        boton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminarActionPerformed(evt);
            }
        });

        boton_aniadir.setText("Añadir Caja");
        boton_aniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aniadirActionPerformed(evt);
            }
        });

        boton_consultar.setText("Consultar Cajas");
        boton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_consultarActionPerformed(evt);
            }
        });

        peso_neto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        peso_neto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peso_neto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        texto_num_cajas.setLabelFor(num_caja);
        texto_num_cajas.setText("Número de Cajas tipo 1:");

        num_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_cajaActionPerformed(evt);
            }
        });

        reset.setText("Hacer nueva destaración");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        texto_cod_palet.setLabelFor(cod_palet);
        texto_cod_palet.setText("Código de Palet:");

        texto_num_palet.setText("Número de Palets:");

        texto_modificar_palet.setText("Introduzca el código del palet a modificar:");

        boton_modificar_palet.setText("Modificar Palet");
        boton_modificar_palet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modificar_paletActionPerformed(evt);
            }
        });

        boton_aniadir_palet.setText("Añadir Palet");
        boton_aniadir_palet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_aniadir_paletActionPerformed(evt);
            }
        });

        texto_eliminar_palet.setText("Introduzca el código del palet a eliminar:");

        boton_eliminar_palet.setText("Eliminar Palet");
        boton_eliminar_palet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_eliminar_paletActionPerformed(evt);
            }
        });

        boton_consultar_palet.setText("Consultar Palets");
        boton_consultar_palet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_consultar_paletActionPerformed(evt);
            }
        });

        text_cod_caja1.setText("Código de Caja tipo 2:");

        text_num_caja1.setText("Número de Cajas tipo 2:");

        boton_elegir.setText("Elegir");
        boton_elegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_elegirActionPerformed(evt);
            }
        });

        boton_capturar_pantalla.setText("Capturar pantalla");
        boton_capturar_pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_capturar_pantallaActionPerformed(evt);
            }
        });

        ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaActionPerformed(evt);
            }
        });

        save_result.setText("Guardar Resultado:");

        boton_imprimir_pantalla.setText("Imprimir pantalla");
        boton_imprimir_pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_imprimir_pantallaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo_peso)
                            .addComponent(titulo_cod_caja)
                            .addComponent(texto_num_cajas)
                            .addComponent(text_cod_caja1)
                            .addComponent(text_num_caja1)
                            .addComponent(texto_num_palet)
                            .addComponent(texto_cod_palet))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cod_palet, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(num_caja1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod_caja1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod_caja)
                                    .addComponent(num_caja)
                                    .addComponent(peso_bruto, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(peso_neto, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(titulo_neto))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(boton_elegir))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(boton_destarar)
                                                .addGap(18, 18, 18)
                                                .addComponent(reset))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(boton_capturar_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(boton_imprimir_pantalla))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(94, 94, 94)
                                        .addComponent(save_result))))
                            .addComponent(num_palets, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(opciones)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo_modificar)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cod_caja_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cod_caja_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boton_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(boton_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(titulo_eliminar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(texto_modificar_palet)
                                    .addComponent(texto_eliminar_palet))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cod_palet_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(cod_palet_eliminar))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boton_modificar_palet, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(boton_eliminar_palet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_aniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_aniadir_palet, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_consultar_palet))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_inicio)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(titulo_inicio)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peso_bruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_cod_caja)
                            .addComponent(cod_caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto_num_cajas)
                            .addComponent(num_caja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_cod_caja1)
                            .addComponent(cod_caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(save_result))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_num_caja1)
                            .addComponent(num_caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto_cod_palet)
                            .addComponent(cod_palet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(texto_num_palet)
                            .addComponent(num_palets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(opciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titulo_neto)
                                .addGap(12, 12, 12)
                                .addComponent(peso_neto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boton_destarar)
                                    .addComponent(reset)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boton_elegir))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_capturar_pantalla)
                            .addComponent(boton_imprimir_pantalla))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_modificar)
                    .addComponent(cod_caja_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_modificar)
                    .addComponent(boton_aniadir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_eliminar)
                    .addComponent(cod_caja_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_eliminar)
                    .addComponent(boton_consultar))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_aniadir_palet)
                    .addComponent(boton_modificar_palet)
                    .addComponent(cod_palet_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_modificar_palet))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_eliminar_palet)
                    .addComponent(cod_palet_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_eliminar_palet)
                    .addComponent(boton_consultar_palet))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peso_brutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_brutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_brutoActionPerformed

    private void cod_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_cajaActionPerformed

    private void boton_destararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_destararActionPerformed
        String bruto = peso_bruto.getText();
        if(bruto.matches("[0-9]+") ) { // Compruebo peso bruto
            String codigo = cod_caja.getText();
            if(codigo.matches("[0-9]+") || codigo.isEmpty()) {  // Compruebo código de caja de tipo 1
               String Ncajas = num_caja.getText();
               if(Ncajas.matches("[0-9]+") || Ncajas.isEmpty()) {  // Compruebo que se ha introducido un número en el número de cajas de tipo 1
                  String codigo_palet = cod_palet.getText();
                  if(codigo_palet.matches("[0-9]+") || codigo_palet.isEmpty()) {  // Compruebo código de palet
                    String Npalets = num_palets.getText();
                    if(Npalets.matches("[0-9]+") || Npalets.isEmpty()) {  // Compruebo que se ha introducido un número en el número de palets
                        String codigo1 = cod_caja1.getText();
                        if(codigo1.matches("[0-9]+") || codigo1.isEmpty()) {  // Compruebo código de caja de tipo 2
                            String Ncajas1 = num_caja1.getText();
                            if(Ncajas1.matches("[0-9]+") || Ncajas1.isEmpty()) {  // Compruebo que se ha introducido un número en el número de cajas de tipo 2
                                OperacionesBD o = new OperacionesBD();
                                    try {
                                        String m = ""; 
                                        if(!codigo.isEmpty() && !Ncajas.isEmpty() && !codigo1.isEmpty() && !Ncajas1.isEmpty() && !codigo_palet.isEmpty() && !Npalets.isEmpty()) m = o.destarar(bruto,codigo,Ncajas,codigo1,Ncajas1,codigo_palet,Npalets);
                                        else if(!codigo.isEmpty() && !Ncajas.isEmpty() && codigo1.isEmpty() && Ncajas1.isEmpty() && codigo_palet.isEmpty() && Npalets.isEmpty()) m = o.destarar(bruto, codigo, Ncajas, "", "", "", ""); 
                                        else if(codigo.isEmpty() && Ncajas.isEmpty() && codigo1.isEmpty() && Ncajas1.isEmpty() && !codigo_palet.isEmpty() && !Npalets.isEmpty()) m = o.destarar(bruto, "", "", "", "",codigo_palet, Npalets);
                                        else if(!codigo.isEmpty() && !Ncajas.isEmpty() && codigo1.isEmpty() && Ncajas1.isEmpty() && !codigo_palet.isEmpty() && !Npalets.isEmpty()) m = o.destarar(bruto,codigo,Ncajas,"","",codigo_palet,Npalets);
                                        else if(!codigo.isEmpty() && !Ncajas.isEmpty() && !codigo1.isEmpty() && !Ncajas1.isEmpty() && codigo_palet.isEmpty() && Npalets.isEmpty()) m = o.destarar(bruto,codigo,Ncajas,codigo1,Ncajas1,"","");

                                        if(!m.isEmpty()) {
                                            if(m.contains("error")) JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
                                            else peso_neto.setText(m + " KG");
                                        }
                                        else JOptionPane.showMessageDialog(rootPane,"No está registrado ese código de caja o de palet, o bien hay campos incompletos");
                                    } catch (ClassNotFoundException | SQLException ex) {
                                        Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                                    } 
                            }
                            else JOptionPane.showMessageDialog(rootPane,"Debe introducir el número de cajas de tipo 2");
                        }
                        else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de caja de tipo 2 que es numérico");
                    }
                    else JOptionPane.showMessageDialog(rootPane,"Debe introducir el número de palets");
                  }
                  else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de palet que es numérico");
               }
               else JOptionPane.showMessageDialog(rootPane,"Debe introducir el número de cajas de tipo 1");
            }
            else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de caja de tipo 1 que es numérico");
        }
        else JOptionPane.showMessageDialog(rootPane,"El peso bruto debe ser un número entero");
    }//GEN-LAST:event_boton_destararActionPerformed

    private void cod_caja_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_caja_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_caja_modificarActionPerformed

    private void boton_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificarActionPerformed
        // Compruebo código de caja
        codigo_caja = cod_caja_modificar.getText();
        if(codigo_caja.matches("[0-9]+")) { // Compruebo código
            OperacionesBD o = new OperacionesBD();
            try {
                boolean [] b = o.existe_id(codigo_caja,1);
                if(b[0]) {
                    if(b[1]) {
                        ModificarCaja m = new ModificarCaja();
                        m.setVisible(true);
                        this.dispose();
                    }
                    else JOptionPane.showMessageDialog(rootPane,"No existe ese código de caja");
                }
                else JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de caja que es numérico");
        
        cod_caja_modificar.setText("");
    }//GEN-LAST:event_boton_modificarActionPerformed

    private void cod_caja_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod_caja_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod_caja_eliminarActionPerformed

    private void boton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminarActionPerformed
        // Compruebo código de caja
        codigo_caja = cod_caja_eliminar.getText();
        if(codigo_caja.matches("[0-9]+")) { // Compruebo código
            OperacionesBD o = new OperacionesBD();
            try {
                String s = o.removeCaja(codigo_caja);
                if(s.contains("error")) JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
                else JOptionPane.showMessageDialog(rootPane,"Caja número " + codigo_caja + " eliminada con éxito");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de caja que es numérico");
        cod_caja_eliminar.setText("");
    }//GEN-LAST:event_boton_eliminarActionPerformed

    private void boton_aniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aniadirActionPerformed
        AniadirCaja a = new AniadirCaja();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_aniadirActionPerformed

    private void boton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_consultarActionPerformed
        ConsultarCajas c = null;
        try {
            c = new ConsultarCajas();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);
    }//GEN-LAST:event_boton_consultarActionPerformed

    private void num_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_cajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num_cajaActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        peso_bruto.setText("");
        cod_caja.setText("");
        num_caja.setText("");
        cod_caja1.setText("");
        num_caja1.setText("");
        peso_neto.setText("");
        cod_palet.setText("");
        num_palets.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void boton_aniadir_paletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_aniadir_paletActionPerformed
        AniadirPalet a = new AniadirPalet();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_aniadir_paletActionPerformed

    private void boton_consultar_paletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_consultar_paletActionPerformed
        ConsultarPalets c = null;
        try {
            c = new ConsultarPalets();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        c.setVisible(true);
    }//GEN-LAST:event_boton_consultar_paletActionPerformed

    private void boton_modificar_paletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modificar_paletActionPerformed
        // Compruebo código de palet
        codigo_palet = cod_palet_modificar.getText();
        if(codigo_palet.matches("[0-9]+")) { // Compruebo código
            OperacionesBD o = new OperacionesBD();
            try {
                boolean [] b = o.existe_id(codigo_palet,2);
                if(b[0]) {
                    if(b[1]) {
                        ModificarPalet m = new ModificarPalet();
                        m.setVisible(true);
                        this.dispose();
                    }
                    else JOptionPane.showMessageDialog(rootPane,"No existe ese código de caja");
                }
                else JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de palet que es numérico");
        
        cod_palet_modificar.setText("");
    }//GEN-LAST:event_boton_modificar_paletActionPerformed

    private void boton_eliminar_paletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_eliminar_paletActionPerformed
        // Compruebo código de palet
        codigo_palet = cod_palet_eliminar.getText();
        if(codigo_palet.matches("[0-9]+")) { // Compruebo código
            OperacionesBD o = new OperacionesBD();
            try {
                String s = o.removePalet(codigo_palet);
                if(s.contains("error")) JOptionPane.showMessageDialog(rootPane,"No está conectado a la base de datos");
                else JOptionPane.showMessageDialog(rootPane,"Palet número " + codigo_palet + " eliminado con éxito");
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(rootPane,"Debe introducir un código de palet que es numérico");
        cod_palet_eliminar.setText("");
    }//GEN-LAST:event_boton_eliminar_paletActionPerformed

    private void boton_elegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_elegirActionPerformed
        JFileChooser elector = new JFileChooser();
        elector.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int r = elector.showOpenDialog(null);
        File f = elector.getSelectedFile();
        if(r == JFileChooser.APPROVE_OPTION) { // Si le da a aceptar
            nombre_directorio = f.getAbsolutePath();
            ruta.setText(nombre_directorio);
        }
    }//GEN-LAST:event_boton_elegirActionPerformed

    private void rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaActionPerformed

    private void boton_capturar_pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_capturar_pantallaActionPerformed
        String r = ruta.getText();
        if(!r.isEmpty()) {
            ruta.setText("");
            Resultado res = new Resultado();
            res.capturarPantalla(r,this.getLocation().x,this.getLocation().y,
                                this.getWidth(),this.getHeight());
        }
        else JOptionPane.showMessageDialog(rootPane,"Elija el directorio dónde quiere almacenar la captura");
    }//GEN-LAST:event_boton_capturar_pantallaActionPerformed

    private void boton_imprimir_pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_imprimir_pantallaActionPerformed
        String r = ruta.getText();
        if(!r.isEmpty()) {
            ruta.setText("");
            Resultado res = new Resultado();
            try {
                res.imprimirPantalla(r,this.getLocation().x,this.getLocation().y,
                        this.getWidth(),this.getHeight());
            } catch (IOException | PrinterException ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else JOptionPane.showMessageDialog(rootPane,"Elija el directorio dónde quiere almacenar la captura");
    }//GEN-LAST:event_boton_imprimir_pantallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_aniadir;
    private javax.swing.JButton boton_aniadir_palet;
    private javax.swing.JButton boton_capturar_pantalla;
    private javax.swing.JButton boton_consultar;
    private javax.swing.JButton boton_consultar_palet;
    private javax.swing.JButton boton_destarar;
    private javax.swing.JButton boton_elegir;
    private javax.swing.JButton boton_eliminar;
    private javax.swing.JButton boton_eliminar_palet;
    private javax.swing.JButton boton_imprimir_pantalla;
    private javax.swing.JButton boton_modificar;
    private javax.swing.JButton boton_modificar_palet;
    private javax.swing.JTextField cod_caja;
    private javax.swing.JTextField cod_caja1;
    private javax.swing.JTextField cod_caja_eliminar;
    private javax.swing.JTextField cod_caja_modificar;
    private javax.swing.JTextField cod_palet;
    private javax.swing.JTextField cod_palet_eliminar;
    private javax.swing.JTextField cod_palet_modificar;
    private javax.swing.JTextField num_caja;
    private javax.swing.JTextField num_caja1;
    private javax.swing.JTextField num_palets;
    private javax.swing.JLabel opciones;
    private javax.swing.JTextField peso_bruto;
    private javax.swing.JLabel peso_neto;
    private javax.swing.JButton reset;
    private javax.swing.JTextField ruta;
    private javax.swing.JLabel save_result;
    private javax.swing.JLabel text_cod_caja1;
    private javax.swing.JLabel text_num_caja1;
    private javax.swing.JLabel texto_cod_palet;
    private javax.swing.JLabel texto_eliminar_palet;
    private javax.swing.JLabel texto_modificar_palet;
    private javax.swing.JLabel texto_num_cajas;
    private javax.swing.JLabel texto_num_palet;
    private javax.swing.JLabel titulo_cod_caja;
    private javax.swing.JLabel titulo_eliminar;
    private javax.swing.JLabel titulo_inicio;
    private javax.swing.JLabel titulo_modificar;
    private javax.swing.JLabel titulo_neto;
    private javax.swing.JLabel titulo_peso;
    // End of variables declaration//GEN-END:variables
}
