package Destarador;

import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alber
 */
public class ModificarCaja extends javax.swing.JFrame {

    private String nombre_archivo;
    private String codigoCaja;
    
    /**
     * Creates new form ModificarCaja
     */
    public ModificarCaja() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Inicio i = new Inicio();
        codigoCaja = i.codigo_caja;
        titulo.setText("Datos de la caja número " + codigoCaja);
        
        this.setTitle("Modificar Caja");
        
        boton_imagen.setVisible(false);
        
        OperacionesBD o = new OperacionesBD();
        ArrayList<String> a = o.showCaja(codigoCaja);

        nombre.setText(a.get(0));
        peso.setText(a.get(1));
        ruta.setText(a.get(2));
        
        if(ruta.getText().isEmpty()) boton_borrar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        titulo_nombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        titulo_peso = new javax.swing.JLabel();
        peso = new javax.swing.JTextField();
        boton_cambiar_nombre = new javax.swing.JButton();
        boton_cambiar_peso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_inicio = new javax.swing.JButton();
        ruta = new javax.swing.JTextField();
        boton_elector = new javax.swing.JButton();
        boton_imagen = new javax.swing.JButton();
        boton_borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 153, 204));

        titulo_nombre.setLabelFor(nombre);
        titulo_nombre.setText("Nombre:");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        titulo_peso.setLabelFor(peso);
        titulo_peso.setText("Peso:");

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });

        boton_cambiar_nombre.setText("Cambiar");
        boton_cambiar_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cambiar_nombreActionPerformed(evt);
            }
        });

        boton_cambiar_peso.setText("Cambiar");
        boton_cambiar_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cambiar_pesoActionPerformed(evt);
            }
        });

        jLabel1.setText("Imagen:");

        boton_inicio.setText("Ir a inicio");
        boton_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_inicioActionPerformed(evt);
            }
        });

        ruta.setEditable(false);
        ruta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutaActionPerformed(evt);
            }
        });

        boton_elector.setText("Elegir");
        boton_elector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_electorActionPerformed(evt);
            }
        });

        boton_imagen.setText("Cambiar");
        boton_imagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_imagenActionPerformed(evt);
            }
        });

        boton_borrar.setText("Borrar");
        boton_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo_nombre)
                            .addComponent(titulo_peso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(peso, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton_borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_cambiar_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_cambiar_peso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_elector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_imagen)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(boton_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_nombre)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cambiar_nombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_peso)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cambiar_peso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_elector)
                    .addComponent(boton_imagen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(boton_inicio)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void boton_cambiar_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cambiar_pesoActionPerformed
        String p = peso.getText();
        if(p.matches("[0-9]+[.][0-9]+") || p.matches("[0-9]+")) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.modificarCaja(p,codigoCaja,2);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ModificarCaja.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio de peso de la caja se ha realizado con éxito");
        }
        else JOptionPane.showMessageDialog(rootPane,"El peso puede ser un número entero (135) ó decimal (135.46)");
    }//GEN-LAST:event_boton_cambiar_pesoActionPerformed

    private void boton_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_inicioActionPerformed
        Inicio i = new Inicio();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_inicioActionPerformed

    private void rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaActionPerformed

    private void boton_electorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_electorActionPerformed
        JFileChooser elector = new JFileChooser();
        elector.setFileFilter(new FileNameExtensionFilter("Imágenes","jpeg","jpg","gif","bmp","png"));
        int r = elector.showOpenDialog(null);
        File f = elector.getSelectedFile();
        if(r == JFileChooser.APPROVE_OPTION) {
            nombre_archivo = f.getAbsolutePath();
            ruta.setText(nombre_archivo);
            if(!ruta.getText().isEmpty()) boton_imagen.setVisible(true);
        }
    }//GEN-LAST:event_boton_electorActionPerformed

    private void boton_imagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_imagenActionPerformed
        String path = ruta.getText();
        if(!path.isEmpty()) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.modificarCaja(path,codigoCaja,3);
                boton_borrar.setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ModificarCaja.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio de imagen de la caja se ha realizado con éxito");
        }
    }//GEN-LAST:event_boton_imagenActionPerformed

    private void boton_cambiar_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cambiar_nombreActionPerformed
        String name = nombre.getText();
        if(!name.isEmpty()) {
            OperacionesBD o = new OperacionesBD();
            try {
                o.modificarCaja(name,codigoCaja,1);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ModificarCaja.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane,"El cambio de nombre de la caja se ha realizado con éxito");
        }
        else JOptionPane.showMessageDialog(rootPane,"Introduzca un nombre");
    }//GEN-LAST:event_boton_cambiar_nombreActionPerformed

    private void boton_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_borrarActionPerformed
        OperacionesBD o = new OperacionesBD();
        try {
            o.modificarCaja("",codigoCaja,3);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ModificarCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(rootPane,"Se ha borrado la imagen de la caja");
        
        ruta.setText("");
        boton_borrar.setVisible(false);
        boton_imagen.setVisible(false);
    }//GEN-LAST:event_boton_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ModificarCaja().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(ModificarCaja.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_borrar;
    private javax.swing.JButton boton_cambiar_nombre;
    private javax.swing.JButton boton_cambiar_peso;
    private javax.swing.JButton boton_elector;
    private javax.swing.JButton boton_imagen;
    private javax.swing.JButton boton_inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField ruta;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo_nombre;
    private javax.swing.JLabel titulo_peso;
    // End of variables declaration//GEN-END:variables
}
